name: Publish to npm and Yarn

on:
  pull_request:
    types: [closed]

jobs:
  publish:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' # or your preferred Node.js version
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: npm install

    - name: Extract version from package.json
      id: extract-version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "PACKAGE_VERSION=$VERSION" >> $GITHUB_ENV
        echo "Extracted version: $VERSION"

    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Publish to Yarn (Optional)
      run: |
        yarn publish --new-version ${{ env.PACKAGE_VERSION }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
